<?php include $phireHeader; ?>
    <h1 class="categories-header"><?=$title; ?> : <span id="title-span"><?=$category_title; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'categories', 'add')): ?>
        <nav><a href="<?=$phireUri; ?>/categories/add">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri; ?>/categories">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include $phireFooter; ?>
