<?php include $phireHeader; ?>
    <h1 class="categories-header"><?=$title; ?></h1>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri; ?>/categories">Back</a></nav>
    </nav>
<?php if (count($content) > 0): ?>
<?php if ($acl->isAllowed($user->role, 'categories', 'process')): ?>
    <form id="categories-process-form" action="<?=$phireUri . '/categories/process'; ?>" method="post">
<?php endif; ?>
    <table class="data-table" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Type</th>
            <th class="text-center">Order</th>
            <th class="text-center"><?php if ($acl->isAllowed($user->role, 'categories', 'process')): ?><input type="checkbox" name="checkall" id="checkall" value="process_categories" /><?php else: ?>&nbsp;<?php endif; ?></th>
        </tr>
<?php $i = 1; ?>
<?php foreach ($content as $c): ?>
        <tr>
            <td><?=$c->id; ?></td>
            <td><?php
if (isset($c->name)):
    echo $c->name;
elseif (isset($c->title)):
    echo $c->title;
else:
    echo '[ N/A ]';
endif;
?></td>
            <td><?=$c->type; ?></td>
            <td class="text-center"><input type="text" name="order_<?=$c->id; ?>" value="<?=(int)$c->order; ?>" class="module-order" size="2" /></td>
            <td class="text-center"><?php if ($acl->isAllowed($user->role, 'categories', 'process')): ?><input type="checkbox" name="process_categories[]" id="process_categories<?=$i++; ?>" value="<?=$c->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
        </tr>
<?php endforeach; ?>
    </table>
<?php if ($acl->isAllowed($user->role, 'categories', 'process')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Process" /><input type="hidden" name="category_id" value="<?=$cid; ?>" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
    <p>There are currently no content in this category.</p>
<?php endif; ?>
<?php include $phireFooter; ?>
