<?php include $phireHeader; ?>
    <h1 class="categories-header"><?=$title; ?></h1>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri; ?>/categories">Back</a></nav>
    </nav>
<?php if (count($items) > 0): ?>
<?php if ($acl->isAllowed($user->role, 'categories', 'process')): ?>
    <form id="categories-process-form" action="<?=$phireUri . '/categories/process'; ?>" method="post">
<?php endif; ?>
    <table class="data-table" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Type</th>
            <th class="text-center">Order</th>
            <th class="text-center"><?php if ($acl->isAllowed($user->role, 'categories', 'process')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_category_items" /><?php else: ?>&nbsp;<?php endif; ?></th>
        </tr>
<?php $i = 1; ?>
<?php foreach ($items as $it): ?>
        <tr>
            <td><?=$it['item_id']; ?></td>
            <td><?=$it['title']; ?></td>
            <td><?=$it['type']; ?></td>
            <td class="text-center"><input type="text" name="order_<?=$it['type']; ?>_<?=$it['item_id']; ?>" value="<?=(int)$it['order']; ?>" class="module-order" size="2" /></td>
            <td class="text-center"><?php if ($acl->isAllowed($user->role, 'categories', 'process')): ?><input type="checkbox" name="rm_category_items[]" id="rm_category_items<?=$i++; ?>" value="<?=$it['type']; ?>_<?=$it['item_id']; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
        </tr>
<?php endforeach; ?>
    </table>
<?php if ($acl->isAllowed($user->role, 'categories', 'process')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Process" /><input type="hidden" name="category_id" value="<?=$cid; ?>" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
    <p>There are currently no items in this category.</p>
<?php endif; ?>
<?php include $phireFooter; ?>
