<!DOCTYPE html>
<html>

<head>

    <title><?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="all" />

</head>

<body>
    <h1><?=$title; ?></h1>
    <p><?=$category_breadcrumb; ?></p>
<?=$pages;?>
<?php if (isset($items) && (count($items) > 0)): ?>
<?php foreach ($items as $item): ?>
    <div class="item-div">
        <h3><?=$item->title; ?></h3>
<?php if (isset($item->file)): ?>
        <p><a href="<?=$base_path . $content_path . '/' . $item->library_folder . '/' . $item->file; ?>"><img src="<?=$item->icon; ?>" /></a></p>
<?php elseif (isset($item->uri)): ?>
        <p><a href="<?=$item->uri; ?>"><?=$item->uri; ?></a></p>
<?php endif; ?>
    </div>
<?php endforeach; ?>
<?php endif; ?>
<?=$category_nav; ?>
</body>

</html>
